### ISSUE TITLE
暗号プライスを Span<byte> で扱う EncryptPrice / DecryptPrice の追加

### ISSUE THREAD

**Issue by in-async** [in-async/AuthorizedBuyersHelpers#4]
暗号プライスを、Base64Url でエンコードする前の `Span<byte>` で扱う API を追加するかどうか。
下記のイメージ:
```cs
public static bool TryEncryptPrice(this ABCrypto crypto, decimal price, in Span<byte> cipherBytes, out int bytesWritten);

public static bool TryDecryptPrice(this ABCrypto crypto, in ReadOnlySpan<byte> cipherBytes, out decimal price);
```

**Comment by in-async** [comment]
`TryEncryptPrice()` に渡す `cipherBytes` のキャパシティを呼び出し側が知る必要があるのが、あまりスマートじゃない。

**Comment by in-async** [comment]
```cs
public static class ABCryptoPriceExtensions {
    ...
}
```
を
```cs
public static class ABPriceCrypto {
    public const int CipherSize = ABCrypto.OverheadSize + PricePayloadSize;
    ...
}
```
とかにすれば、
```cs
Span<byte> cipherBytes = stackalloc byte[ABPriceCrypto.CipherSize];
var success = crypto.TryEncryptPrice(price, cipherBytes, out var bytesWritten);
Debug.Assert(success);
Debug.Assert(bytesWritten == ABPriceCrypto.CipherSize);
```
で呼べて、まあまあか。

**Comment by mechiru** [comment]
@in-async 
https://github.com/in-async/AuthorizedBuyersHelpers/issues/4#issuecomment-523039983 この記述はパッケージ側に書く予定ですか？それとも利用者側が書きますか？

**Comment by im-kashi** [comment]
@mechiru 
既存の [ABCryptoPriceExtensions.cs](https://github.com/in-async/AuthorizedBuyersHelpers/blob/master/src/AuthorizedBuyersHelpers/ABCryptoPriceExtensions.cs) を更新するつもりです。

ただ、Authorized Buyers の汎用的な暗号化スキームを表す ABCrypto の上にプライス用の暗号・復号処理を拡張しているだけですので、プライスに限らずこの手の処理は利用者側が書いても全然問題ないですよ。

**Comment by in-async** [comment]
@mechiru 
[ABCryptoPriceExtensions](https://github.com/in-async/AuthorizedBuyersHelpers/blob/master/src/AuthorizedBuyersHelpers/ABCryptoPriceExtensions.cs) を更新するつもりです。

ただ、Authorized Buyers の汎用的な暗号化スキームの上にプライスを暗号・復号する処理を拡張しているだけですので、プライスに限らずこの手の処理は `ABCrypto` を使って利用者側で書いてしまっても良いと思いますよ。

**Comment by mechiru** [comment]
@in-async 
パッケージの利用者側として以下の想定でいいですか？
* 1byte目を特定の目的で使用しているコードです。
```csharp
var crypto = new ABCrypto(new StubABCryptoKeys(/* some valid keys */));

Span<byte> span = stackalloc byte[ABPriceCrypto.CipherSize + 1];
span[0] = 7;
crypto.TryEncryptPrice(100, span.Slice(1), out _);
crypto.TryDecryptPrice(span.Slice(1), out var price);
```

**Comment by in-async** [comment]
@mechiru 
`TryDecryptPrice()` は問題ないです。
`TryEncryptPrice()` の方は最も詳細なオーバーロードの追加になりそうなので、初期化ベクトルを受ける形になります (冒頭のイメージ シグネチャとちょっと異なりますが...)。

なので、想定コードは下記のようになるかと。
```cs
// new
Span<byte> iv = stackalloc byte[ABCrypto.IVSize];
ABIV.TryCreate(iv, out _);

Span<byte> span = stackalloc byte[ABPriceCrypto.CipherSize + 1];
span[0] = 7;
crypto.TryEncryptPrice(100, iv /* new */, span.Slice(1), out _);
crypto.TryDecryptPrice(span.Slice(1), out var price);
```

**Comment by in-async** [comment]
補足ですが、Authorized Buyers の暗号化に使用する IV は絶対にそのフォーマットじゃないとダメってものじゃないようなので (まあただの初期化ベクトルなので)、`ABIV` は使わないで自前で作っても良いと思います。

**Comment by mechiru** [comment]
@in-async https://github.com/in-async/AuthorizedBuyersHelpers/issues/4#issuecomment-523305950 でやりたい事はできそうなので、上記でいいと思います。
